/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BTab: typeof import('bootstrap-vue-next')['BTab']
    BTabs: typeof import('bootstrap-vue-next')['BTabs']
    TabElement: typeof import('./src/components/tab/TabElement.vue')['default']
    TabItem: typeof import('./src/components/tab/TabItem.vue')['default']
  }
}
