/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BTab: typeof import('bootstrap-vue-next')['BTab']
    BTabs: typeof import('bootstrap-vue-next')['BTabs']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    HoyolabTabContent: typeof import('./src/components/TabContent/HoyolabTabContent.vue')['default']
    TabComponent: typeof import('./src/components/TabComponent.vue')['default']
    TwitterTabContent: typeof import('./src/components/TabContent/TwitterTabContent.vue')['default']
    VersionDropdown: typeof import('./src/components/VersionDropdown.vue')['default']
    WebsiteTabContent: typeof import('./src/components/TabContent/WebsiteTabContent.vue')['default']
    YoutubeTabContent: typeof import('./src/components/TabContent/YoutubeTabContent.vue')['default']
  }
}
